### ISSUE TITLE
The primitive type names and the literal suffixes are not matched

### ISSUE THREAD

**Issue by lumynou5** [CASC-Lang/CASC#56]
The primitive type names and the literal suffixes are not matched; for example, the type is `i32` but the literal is `1I`.

**Comment by ChAoSUnItY** [comment]
Ok, so it went out in CASC number naming covention is not that easily to describe. For all integers, inlcuding byte, short, int, and long, they are all sharing a integer prefix which is `i` in this case. So for i32, it shouldn't be `1I`, instead, it should be `1i32`.

And so on, to specify a number literal's type, you should add corresponding type name after it.

**Comment by ChAoSUnItY** [comment]
afaik, this issue had been fixed, as [example](../tree/revamp-v2/examples/sourceA.yk) showed.
